apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r2klwf4x7-nodejs 
  janus-idp.io/tekton: r2klwf4x7-nodejs
  backstage.io/kubernetes-id: r2klwf4x7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r2klwf4x7-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  